name: test
on:
  push:
    paths:
      - .github/workflows/test_config.yml
    branches:
      - productie
      - test
      - ontwikkel
  pull_request:
    paths:
      - .github/workflows/test_config.yml
    branches:
      - productie
      - test
      - ontwikkel
       
jobs:
  create-env:
    name: Test config FEWS-EFCIS
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: "3.10"
          channels: conda-forge,defaults
          auto-activate-base: false
          activate-environment: actions_env
          environment-file: etc/actions_env.yml
      - name: list environment
        run: |
          C:/Miniconda/condabin/conda.bat info --envs
          C:/Miniconda/condabin/conda.bat list
      - name: Install test dependencies
        run: C:/Miniconda/condabin/conda.bat install pytest      
      - name: Test config
        run: pytest tests/test_config.py