name: Run workflow testrun FEWS-EFCIS
on:
  push:
    branches:
      - productie
      - test
      - ontwikkel
  pull_request:
    branches:
      - productie
      - test
      - ontwikkel
      
jobs:
  create-env:
    name: Workflow testrun
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: list directory
        run: ls
      - name: run workflow testrun
        run: wf_testrun/run_wf_testrun.bat
          
      - name: create environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          python-version: "3.10"
          channels: conda-forge,defaults
          auto-activate-base: true
      - name: list environment
        run: |
          C:/Miniconda/condabin/conda.bat info --envs
          C:/Miniconda/condabin/conda.bat list
      - name: Install test dependencies
        run: C:/Miniconda/condabin/conda.bat install pytest      
      - name: Test config
        run: pytest tests/test_wf_test.py