name: Run workflow testrun FEWS-EFCIS
on:
  push:
    branches:
      - productie
      - test
      - ontwikkel
  pull_request:
    branches:
      - productie
      - test
      - ontwikkel
      
jobs:
  create-env:
    name: Workflow testrun
    runs-on: windows-2019
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
        
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: list directory
        run: ls
      - name: run workflow testrun
        run: wf_testrun/run_wf_testrun.bat
      - name: list directory
        run: ls
          
          
